# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_geofence', models.CharField(default='', max_length=200, unique=True)),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('pos_time', models.CharField(default='', max_length=200)),
                ('pos_lat', models.CharField(default='', max_length=200)),
                ('pos_long', models.CharField(default='', max_length=200)),
                ('pos_heading', models.CharField(default='', max_length=200)),
                ('pos_address', models.CharField(default='', max_length=200)),
                ('geo_category', models.CharField(choices=[('normal', 'normal'), ('parent', 'parent'), ('child', 'child')], default='normal', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('driver_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geofence', models.CharField(default='', max_length=200, unique=True)),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('pos_time', models.CharField(default='', max_length=200)),
                ('pos_lat', models.CharField(default='', max_length=200)),
                ('pos_long', models.CharField(default='', max_length=200)),
                ('pos_heading', models.CharField(default='', max_length=200)),
                ('pos_address', models.CharField(default='', max_length=200)),
                ('geo_category', models.CharField(choices=[('normal', 'normal'), ('parent', 'parent'), ('child', 'child')], default='normal', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(default='', max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('geo_time', models.CharField(default='', max_length=200)),
                ('event_duration', models.IntegerField(default=0)),
                ('geotype', models.CharField(default='', max_length=200)),
                ('child_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geofence.Child')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geofence.Driver')),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geofence.Geofence')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('plate', models.CharField(default='', max_length=200)),
                ('child_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('geo_time', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('event_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('geotype', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('child_geotype', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('response', models.CharField(blank=True, max_length=200, null=True)),
                ('child_response', models.CharField(blank=True, max_length=200, null=True)),
                ('child_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geofence.Child')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geofence.Driver')),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geofence.Geofence')),
            ],
        ),
    ]
